### ISSUE TITLE
Sometimes receiving the russian website although I don't speak russian

### ISSUE THREAD

**Issue by mineo** [abh/ntppool#111]
While browsing http://www.pool.ntp.org/zone/europe (reached by going to http://www.pool.ntp.org/en/, clicking on "easy to use" in the introduction, clicking on "europe" or simply clicking the link here) I noticed that the links in the sidebar sometimes (but not always, that would have been too easy) link to the russian version of the website (the content itself is english, although that might just be because it hasn't been translated yet).

These are the request headers:
> GET /zone/europe HTTP/1.1
> Host: www.pool.ntp.org
> Connection: keep-alive
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) > Chrome/35.0.1916.153 Safari/537.36
> DNT: 1
> Accept-Encoding: gzip,deflate,sdch
> Accept-Language: en,en-US;q=0.8,de;q=0.6

These are the response headers:
> HTTP/1.1 200 OK
> Date: Thu, 19 Jun 2014 11:00:49 GMT
> Content-Type: text/html; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Cache-Control: s-maxage=900, maxage=1800
> Last-Modified: Thu, 19 Jun 2014 05:32:23 GMT
> P3P: CP="There's no P3P policy. Learn why here: http://www.w3.org/P3P/"
> X-NPV: c92d928c-M (ntplax4)
> X-UA-Compatible: IE=9
> X-Varnish: 508959951
> Age: 0
> Via: 1.1 varnish
> Vary: Accept-Language
> X-Varnish-Language: ru
> X-Served-By: ntplax8.ntppool.net
> X-Cache: MISS
> X-Cache-Hits: 0
> Server: NetDNA-cache/2.2
> X-Cache: HIT
> Content-Encoding: gzip

The remote address Chromium shows is 108.161.188.192:80, so I guess it's using my IPv4 adress which is inside 141.24.0.0/16 (I do see some requests to ipv{4,64,6}.v6test.develooper.com, the latter two use v6 where I'm inside  2001:638:904::/48).

As you can see, my browser does not actually indicate at any point in time that I would be able to understand a russian website.

(Force) reloading the website does not always help.

The same thing happens in Firefox but I didn't find a way to copy the headers in its developer tools :(

**Comment by abh** [comment]
Hello! I only just saw this now. I wonder if the CDN is ignoring the Vary header. :-/  Does it still happen?

**Comment by mineo** [comment]
That's a good question - I remember that when I reported this, I could reproduce it with less than 10 reloads (ignoring the browser cache) of that website, but now that doesn't work anymore.

From what I understand of HTTP caching (and that's not much) the `X-Cache: MISS` header would indicate that I'm getting sent a fresh response, no?

**Comment by mineo** [comment]
I'll close this ticket because I couldn't reproduce the behaviour over the last few days.
