### ISSUE TITLE
docker link broken

### ISSUE THREAD

**Issue by akhepcat** [abh/ntppool#155]
both  docker/app  and docker/sh  point to a non-existent or non-public repository.

docker run -t -i -v /usr/local/src/ntppool:/ntppool -p 8299:8299 quay.io/ntppool/app-base:dev ./docker-run

fails with 
docker: Error: Status 403 trying to pull repository ntppool/app-base: "{\"error\": \"Permission Denied\"}".

Browsing at https://quay.io/organization/ntppool   does not show the app-base repository, and it is unclear which is correct.

This means that it is now impossible to spin up a new test instance of  ntppool for somebody interested in learning about it.

**Comment by abh** [comment]
Thanks! I will have a look at getting the instructions sorted. 

I mostly work on this under minikube / Kubernetes now, but I’d like to keep a docker(-compose) setup working as it takes less resources and is a lot less moving parts to learn thank k8s.

**Comment by akhepcat** [comment]
Haven't used kube at all, so i don't think i could suss out how to get this running under it without a lot of handholding, lol.

Appreciate getting the docker stuff fixed, though, that'll be nice once it's working again.

**Comment by abh** [comment]
Hi @akhepcat -- sorry to not update the issue; I think this should have been fixed since a while ago. Any chance you can try again?

On my laptop I usually develop by just starting the system up with `docker-compose up` and I run the shell script below to start a proxy on port 80 to forward requests to the application:

```
#!/bin/sh

docker stop nginx-proxy
docker rm nginx-proxy

set -ex

docker run \
  -d \
  -p 80:80 \
  -p 443:443 \
  --name nginx-proxy \
  --restart always \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  -v `pwd`/certs:/etc/nginx/certs \
  jwilder/nginx-proxy

docker network connect ntppool_default nginx-proxy

docker logs -f  nginx-proxy
```

**Comment by akhepcat** [comment]
ooh, i'll have to spin up my NTP environment again... I haven't used it for a while.

**Comment by abh** [comment]
another version now is the NTP Pool Helm chart (for Kubernetes):

https://hub.helm.sh/charts/ntppool/ntppool
