### ISSUE TITLE
User Ability To Rename Profile Name

### ISSUE THREAD

**Issue by Jas0n99** [abh/ntppool#170]
Refer to RT# 5124 & 5938 for more info.

Apparently the old system had the ability for users to rename their profile name, from the system-generated random characters to whatever they want (assuming not already in-use).

Example:

Old:
http://www.pool.ntp.org/user/afe2a4v6vi83cbr5r

New:
http://www.pool.ntp.org/user/bobs-ntp-servers

**Comment by Jas0n99** [comment]
This feature has been added in the recent UI update on production.

Going to close as resolved. 👍

**Comment by abh** [comment]
Thanks!
