### ISSUE TITLE
Display bug on: https://www.ntppool.org/zone/@

### ISSUE THREAD

**Issue by Jas0n99** [abh/ntppool#190]
Something is messed up with the list of zones on the following page:

https://www.ntppool.org/zone/@

The list starts out like:
```
Asia/Pacific Region — #ap.pool.ntp.org (0)
— -----.pool.ntp.org (0)
Africa — africa.pool.ntp.org (42)
```
Not only is the Asia/Pacific link showing 0, when you click on it the page's numbers are for "all pool" servers. Not sure what the second one is with '— -----', at least it's not a link.

Probably a small typo in the code for the page...

**Comment by abh** [comment]
what the heck ...  I made this bug in https://github.com/abh/ntppool/commit/b3c87420d73110c9d73a69a0cb2bdbb7fc5a48d4#diff-d36d973ea473beac81b95ca143092ad8 I think.  Not sure how I let that slip by (and glancing at the code I'm not sure how I thought it worked at all, so I need to fix it when I'm more awake!). 🤷‍♂
