### ISSUE TITLE
How about a "0" speed so users can add monitor-only servers?

### ISSUE THREAD

**Issue by Jas0n99** [abh/ntppool#193]
Would it be possible to add a "zero" speed / weight, so that individuals can add / change servers they want as monitor-only? Seems like something people have been asking for more lately.

**Comment by abh** [comment]
Hm -- that's a curious idea.

As you've seen there's no UI or API for the current toggle; my thinking was that there's a resource cost for the NTP Pool to do the monitoring and track the results, but maybe something good would come of it that'd make it worth it.

**Comment by abh** [comment]
I added this feature on the beta site now if you want to try it out and let me know if it seems okay. If you add a server to some obscure zone there (since you have admin access) you can try if it disappears after 5-10 minute when you set the netspeed to zero.

https://manage-beta.grundclock.com/
