### ISSUE TITLE
Bandwidth speed change is broken again for servers you didn't originall add...

### ISSUE THREAD

**Issue by Jas0n99** [abh/ntppool#194]
I swear this was working for a while, but some other code change must have broken it. Changing the bandwidth setting for a server you didn't originally add doesn't work anymore. :(

**Comment by abh** [comment]
I think I fixed it on the beta site in 040b9c1f10a0f1b724b8dbc240d306203851e2a8 (issue #183), which hasn't been pushed to production yet (though I'm working on getting an update ready for that now!).

**Comment by abh** [comment]
I pushed this out a day or two after the update above, so it should be working now.
