### ISSUE TITLE
Unable to choose between vendor and personal servers

### ISSUE THREAD

**Issue by avijc** [abh/ntppool#208]
I'm one of the lucky ones who has a vendor zone.

(Although it's really no longer used -- previously our clients had their own separate internet connections, but now they are all behind one huge VPN with a single exit point, so we switched our clients to use a NTP server running at that exit point. But I digress.)

Having a vendor zone means there are some changes on the server management page. In particular, there's a dropdown menu between the "NTP Pool Project" logo and "My servers" link, which allows me to select between servers registered to the vendor and servers registered to myself personally. As those servers are in reality run by me, I have chosen to keep them registered to myself personally. The default selection for the dropdown menu is the vendor (id 323). So in order to manage my servers I have needed to select my own personal account first.

The problem is that the dropdown menu no longer works. Clicking it (or rather the default selection, the vendor name) no longer does anything and I can't select to manage the servers in my personal account. I'm not quite sure when it broke, but probably in the last two weeks. I tested this with Chrome and Safari on Mac.

When I view the source code of the page I can see a "dropdown-item active" entry for the company and a "dropdown-item" entry for my personal account, with links to managing both. Clicking my personal link does let me manage my personal servers, so a kind-of workaround for this problem exists.

**Comment by avijc** [comment]
This may be related, but apparently there's some other breakage as well. When I selected to view my own servers using the workaround mentioned above, I can see my servers but I can't change their netspeeds. I can choose the new netspeed from the dropdown menu, but it no longer changes the "Net speed: 500 Mbit" value next to it.

**Comment by avijc** [comment]
From the page source:

```
<script type="text/javascript" src="https://st.ntppool.org/ntppool/cdn/libs/jquery/3/jquery.min.js"></script>
<script type="text/javascript" src="https://st.ntppool.org/ntppool/cdn/libs/popper/1/popper.min.js"></script>
<script type="text/javascript" src="https://st.ntppool.org/ntppool/cdn/libs/bootstrap/4/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://st.ntppool.org/ntppool/js/ntppool-min.vb8aa7f9.js"></script>
```

The first three Javascript links give me a "default backend - 404".

**Comment by abh** [comment]
yeah, good catch -- it should be fixed now!

**Comment by avijc** [comment]
Thanks, works now!
